export var styles = {
  bmBurgerButton: {
    position: "fixed",
    width: "36px",
    height: "25px",
    left: "36px",
    top: "36px",
  },
  bmBurgerBars: {
    background: "#ffff",
    borderRadius: 10,
  },
  bmBurgerBarsHover: {
    background: "#a90000",
  },
  bmCrossButton: {
    height: "24px",
    width: "24px",
  },
  bmCross: {
    background: "#bdc3c7",
  },
  bmMenuWrap: {
    position: "fixed",
    height: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    backdropFilter: "blur(20px)",
    boxShadow: "0px 1px 24px -1px rgba(0, 0, 0, 0.5)",
    borderBottomRightRadius: 16,
    borderTopRightRadius: 16,
  },
  bmMenu: {
    overflow: "hidden",
    padding: "2.5em 1.5em 0",
    fontSize: "1.15em",
  },
  bmMorphShape: {
    fill: "#373a47",
  },
  bmItemList: {
    color: "#b8b7ad",
    padding: "0.8em",
  },
  bmItem: {
    display: "inline-block",
  },
  bmOverlay: {
    background: "rgba(0, 0, 0, 0.3)",
  },
  menuItems: {
    marginTop: 32,
    display: "flex",
    flexDirection: "column",
    height: 200,
    justifyContent: "space-between",
  },
  navBar: {
    position: "absolute",
    top: 0,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    width: "100vw",
    height: 90,
    borderWidth: 10,
    borderColor: "rgba( 255, 255, 255, 0.18 )",
    backdropFilter: "blur(20px)",
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 16,
    boxShadow: "0px 1px 24px -1px rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  logo: {
    width: 255.5,
    height: 50,
  },
  heroLayout: {
    position: "absolute",
    bottom: 0,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    boxShadow: " 0px 1px 24px -1px rgba(0, 0, 0, 0.5)",
    width: 386,
    height: 220,
    borderTopRightRadius: 16,
    borderTopLeftRadius: 16,
    backdropFilter: "blur(20px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 32,
  },
  virtual: {
    fontSize: 24,
    lineHeight: "36px",
    textDecorationLine: "line-through",
    letterSpacing: 15,
    color: "rgba(255, 255, 255, 0.5)",
    margin: 0,
  },
  tagLine: {
    fontSize: 16,
    fontWeight: "normal",
    lineHeight: "36px",
    letterSpacing: 2,
    color: "rgba(255, 255, 255, 0.5)",
    margin: 0,
    textAlign: "center",
  },
  button: {
    width: 200,
    height: 45,
    backgroundColor: "#9B0000",
    borderRadius: 8,
    // borderColor: "rgba(0, 0, 0,0)",
    // boxShadow: "0px 1px 24px -1px rgba(0, 0, 0, 0.5)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  googleTrusted: {
    position: "absolute",
    bottom: 32,
    right: 32,
    width: 71,
    height: 99,
  },
};
